### ISSUE TITLE
Need examples of using

### ISSUE THREAD

**Issue by Monabr** [aljazst/Android-Strings.xml-Translator#1]
Please provide it

**Comment by aljazst** [comment]
Hello, 

as mentioned in the readme you just have to open cmd or powershell and run the python command python AndroidStringTranslator.py translateFile. The line "translateFile" will start the the function that does the work. You can also call list-languages to get a list of the language codes.  You just have to add the strings you want to transalate and the APIkey in the same folder as the python script. The values-en folder as seen in the image will be generated when all is translated. Hope this helps.
![Capture](https://user-images.githubusercontent.com/76880102/108357934-61afd300-71ee-11eb-9dcf-16431731290a.PNG)
